INSERT INTO airlines (id, airline_name, airline_code, logo) VALUES
  (1, 'IndiGo', '6E', '/airlines/a4.png'),
  (2, 'Air India', 'AI', '/airlines/a1.png'),
  (3, 'Akasa Air', 'QP', '/airlines/a3.png'),
  (4, 'SpiceJet', 'SG', '/airlines/a2.png'),
  (5, 'Emirates', 'EK', '/airlines/a5.png'),
  (6, 'Qatar Airways', 'QR', '/airlines/a5.png');

INSERT INTO airports (code, city, country, airport_name, state, city_group, popularity) VALUES
  ('DEL', 'New Delhi', 'India', 'Indira Gandhi International Airport', 'Delhi', 'Delhi NCR', 100),
  ('BOM', 'Mumbai', 'India', 'Chhatrapati Shivaji Maharaj International Airport', 'Maharashtra', 'Mumbai Metro', 98),
  ('BLR', 'Bengaluru', 'India', 'Kempegowda International Airport', 'Karnataka', 'Bengaluru', 95),
  ('HYD', 'Hyderabad', 'India', 'Rajiv Gandhi International Airport', 'Telangana', 'Hyderabad', 92),
  ('MAA', 'Chennai', 'India', 'Chennai International Airport', 'Tamil Nadu', 'Chennai', 90),
  ('CCU', 'Kolkata', 'India', 'Netaji Subhas Chandra Bose International Airport', 'West Bengal', 'Kolkata', 88),
  ('AMD', 'Ahmedabad', 'India', 'Sardar Vallabhbhai Patel International Airport', 'Gujarat', 'Ahmedabad', 82),
  ('PNQ', 'Pune', 'India', 'Pune Airport', 'Maharashtra', 'Pune', 80),
  ('GOI', 'Goa', 'India', 'Goa International Airport', 'Goa', 'Goa', 78),
  ('COK', 'Kochi', 'India', 'Cochin International Airport', 'Kerala', 'Kochi', 77),
  ('TRV', 'Thiruvananthapuram', 'India', 'Trivandrum International Airport', 'Kerala', 'Thiruvananthapuram', 70),
  ('LKO', 'Lucknow', 'India', 'Chaudhary Charan Singh International Airport', 'Uttar Pradesh', 'Lucknow', 75),
  ('JAI', 'Jaipur', 'India', 'Jaipur International Airport', 'Rajasthan', 'Jaipur', 72),
  ('ATQ', 'Amritsar', 'India', 'Sri Guru Ram Dass Jee International Airport', 'Punjab', 'Amritsar', 70),
  ('IXC', 'Chandigarh', 'India', 'Chandigarh Airport', 'Chandigarh', 'Chandigarh', 68),
  ('BBI', 'Bhubaneswar', 'India', 'Biju Patnaik International Airport', 'Odisha', 'Bhubaneswar', 66),
  ('GAU', 'Guwahati', 'India', 'Lokpriya Gopinath Bordoloi International Airport', 'Assam', 'Guwahati', 65),
  ('PAT', 'Patna', 'India', 'Jay Prakash Narayan Airport', 'Bihar', 'Patna', 64),
  ('IXR', 'Ranchi', 'India', 'Birsa Munda Airport', 'Jharkhand', 'Ranchi', 63),
  ('RPR', 'Raipur', 'India', 'Swami Vivekananda Airport', 'Chhattisgarh', 'Raipur', 62),
  ('IDR', 'Indore', 'India', 'Devi Ahilya Bai Holkar Airport', 'Madhya Pradesh', 'Indore', 61),
  ('BHO', 'Bhopal', 'India', 'Raja Bhoj Airport', 'Madhya Pradesh', 'Bhopal', 60),
  ('VNS', 'Varanasi', 'India', 'Lal Bahadur Shastri International Airport', 'Uttar Pradesh', 'Varanasi', 59),
  ('IXU', 'Aurangabad', 'India', 'Aurangabad Airport', 'Maharashtra', 'Aurangabad', 58),
  ('STV', 'Surat', 'India', 'Surat Airport', 'Gujarat', 'Surat', 57),
  ('NAG', 'Nagpur', 'India', 'Dr. Babasaheb Ambedkar International Airport', 'Maharashtra', 'Nagpur', 56),
  ('DED', 'Dehradun', 'India', 'Jolly Grant Airport', 'Uttarakhand', 'Dehradun', 55),
  ('GWL', 'Gwalior', 'India', 'Rajmata Vijaya Raje Scindia Airport', 'Madhya Pradesh', 'Gwalior', 50),
  ('JLR', 'Jabalpur', 'India', 'Jabalpur Airport', 'Madhya Pradesh', 'Jabalpur', 48),
  ('UDR', 'Udaipur', 'India', 'Maharana Pratap Airport', 'Rajasthan', 'Udaipur', 54),
  ('IXE', 'Mangaluru', 'India', 'Mangalore International Airport', 'Karnataka', 'Mangaluru', 53),
  ('VTZ', 'Visakhapatnam', 'India', 'Visakhapatnam Airport', 'Andhra Pradesh', 'Visakhapatnam', 52),
  ('RJA', 'Rajahmundry', 'India', 'Rajahmundry Airport', 'Andhra Pradesh', 'Rajahmundry', 45),
  ('TIR', 'Tirupati', 'India', 'Tirupati Airport', 'Andhra Pradesh', 'Tirupati', 44),
  ('TRZ', 'Tiruchirappalli', 'India', 'Tiruchirappalli International Airport', 'Tamil Nadu', 'Tiruchirappalli', 51),
  ('IXM', 'Madurai', 'India', 'Madurai Airport', 'Tamil Nadu', 'Madurai', 49),
  ('CJB', 'Coimbatore', 'India', 'Coimbatore International Airport', 'Tamil Nadu', 'Coimbatore', 50),
  ('IXB', 'Bagdogra', 'India', 'Bagdogra Airport', 'West Bengal', 'Siliguri', 58),
  ('DIB', 'Dibrugarh', 'India', 'Dibrugarh Airport', 'Assam', 'Dibrugarh', 46),
  ('IXA', 'Agartala', 'India', 'Maharaja Bir Bikram Airport', 'Tripura', 'Agartala', 47),
  ('IMF', 'Imphal', 'India', 'Imphal International Airport', 'Manipur', 'Imphal', 46),
  ('IXZ', 'Port Blair', 'India', 'Veer Savarkar International Airport', 'Andaman and Nicobar', 'Port Blair', 48),
  ('SLV', 'Shimla', 'India', 'Shimla Airport', 'Himachal Pradesh', 'Shimla', 30),
  ('KUU', 'Kullu', 'India', 'Kullu Manali Airport', 'Himachal Pradesh', 'Kullu', 32),
  ('IXJ', 'Jammu', 'India', 'Jammu Airport', 'Jammu and Kashmir', 'Jammu', 45),
  ('SXR', 'Srinagar', 'India', 'Sheikh ul Alam International Airport', 'Jammu and Kashmir', 'Srinagar', 46),
  ('IXD', 'Prayagraj', 'India', 'Prayagraj Airport', 'Uttar Pradesh', 'Prayagraj', 44),
  ('JDH', 'Jodhpur', 'India', 'Jodhpur Airport', 'Rajasthan', 'Jodhpur', 45),
  ('BKB', 'Bikaner', 'India', 'Nal Airport', 'Rajasthan', 'Bikaner', 35),
  ('JGA', 'Jamnagar', 'India', 'Jamnagar Airport', 'Gujarat', 'Jamnagar', 40),
  ('BDQ', 'Vadodara', 'India', 'Vadodara Airport', 'Gujarat', 'Vadodara', 55),
  ('GAY', 'Gaya', 'India', 'Gaya Airport', 'Bihar', 'Gaya', 38),
  ('IXL', 'Leh', 'India', 'Kushok Bakula Rimpochee Airport', 'Ladakh', 'Leh', 42),
  ('KNU', 'Kanpur', 'India', 'Kanpur Airport', 'Uttar Pradesh', 'Kanpur', 40),
  ('BHU', 'Bhavnagar', 'India', 'Bhavnagar Airport', 'Gujarat', 'Bhavnagar', 37),
  ('PBD', 'Porbandar', 'India', 'Porbandar Airport', 'Gujarat', 'Porbandar', 34),
  ('RAJ', 'Rajkot', 'India', 'Rajkot Airport', 'Gujarat', 'Rajkot', 39),
  ('JSA', 'Jaisalmer', 'India', 'Jaisalmer Airport', 'Rajasthan', 'Jaisalmer', 33),
  ('IXW', 'Jamshedpur', 'India', 'Sonari Airport', 'Jharkhand', 'Jamshedpur', 32),
  ('IXY', 'Kandla', 'India', 'Kandla Airport', 'Gujarat', 'Kandla', 30),
  ('JFK', 'New York', 'United States', 'John F Kennedy International Airport', 'New York', 'New York Metro', 95),
  ('LGA', 'New York', 'United States', 'LaGuardia Airport', 'New York', 'New York Metro', 82),
  ('EWR', 'Newark', 'United States', 'Newark Liberty International Airport', 'New Jersey', 'New York Metro', 85),
  ('LAX', 'Los Angeles', 'United States', 'Los Angeles International Airport', 'California', 'Los Angeles', 92),
  ('SFO', 'San Francisco', 'United States', 'San Francisco International Airport', 'California', 'San Francisco', 90),
  ('SEA', 'Seattle', 'United States', 'Seattle Tacoma International Airport', 'Washington', 'Seattle', 80),
  ('ORD', 'Chicago', 'United States', 'O Hare International Airport', 'Illinois', 'Chicago', 88),
  ('ATL', 'Atlanta', 'United States', 'Hartsfield Jackson Atlanta International Airport', 'Georgia', 'Atlanta', 89),
  ('DFW', 'Dallas', 'United States', 'Dallas Fort Worth International Airport', 'Texas', 'Dallas', 86),
  ('IAH', 'Houston', 'United States', 'George Bush Intercontinental Airport', 'Texas', 'Houston', 84),
  ('MIA', 'Miami', 'United States', 'Miami International Airport', 'Florida', 'Miami', 83),
  ('BOS', 'Boston', 'United States', 'Logan International Airport', 'Massachusetts', 'Boston', 82),
  ('IAD', 'Washington', 'United States', 'Washington Dulles International Airport', 'Virginia', 'Washington DC', 80),
  ('DCA', 'Washington', 'United States', 'Ronald Reagan Washington National Airport', 'Virginia', 'Washington DC', 78),
  ('MSP', 'Minneapolis', 'United States', 'Minneapolis Saint Paul International Airport', 'Minnesota', 'Minneapolis', 75),
  ('DEN', 'Denver', 'United States', 'Denver International Airport', 'Colorado', 'Denver', 81),
  ('LHR', 'London', 'United Kingdom', 'Heathrow Airport', 'England', 'London Metro', 94),
  ('LGW', 'London', 'United Kingdom', 'Gatwick Airport', 'England', 'London Metro', 86),
  ('STN', 'London', 'United Kingdom', 'Stansted Airport', 'England', 'London Metro', 78),
  ('MAN', 'Manchester', 'United Kingdom', 'Manchester Airport', 'England', 'Manchester', 80),
  ('BHX', 'Birmingham', 'United Kingdom', 'Birmingham Airport', 'England', 'Birmingham', 72),
  ('DXB', 'Dubai', 'United Arab Emirates', 'Dubai International Airport', 'Dubai', 'Dubai', 96),
  ('DWC', 'Dubai', 'United Arab Emirates', 'Al Maktoum International Airport', 'Dubai', 'Dubai', 70),
  ('AUH', 'Abu Dhabi', 'United Arab Emirates', 'Abu Dhabi International Airport', 'Abu Dhabi', 'Abu Dhabi', 84),
  ('SIN', 'Singapore', 'Singapore', 'Changi Airport', 'Singapore', 'Singapore', 92),
  ('BKK', 'Bangkok', 'Thailand', 'Suvarnabhumi Airport', 'Bangkok', 'Bangkok', 90),
  ('DMK', 'Bangkok', 'Thailand', 'Don Mueang International Airport', 'Bangkok', 'Bangkok', 76),
  ('CDG', 'Paris', 'France', 'Charles de Gaulle Airport', 'Ile de France', 'Paris', 90),
  ('ORY', 'Paris', 'France', 'Orly Airport', 'Ile de France', 'Paris', 78),
  ('HND', 'Tokyo', 'Japan', 'Haneda Airport', 'Tokyo', 'Tokyo', 92),
  ('NRT', 'Tokyo', 'Japan', 'Narita International Airport', 'Chiba', 'Tokyo', 86),
  ('YYZ', 'Toronto', 'Canada', 'Toronto Pearson International Airport', 'Ontario', 'Toronto', 85),
  ('YVR', 'Vancouver', 'Canada', 'Vancouver International Airport', 'British Columbia', 'Vancouver', 82),
  ('SYD', 'Sydney', 'Australia', 'Sydney Kingsford Smith Airport', 'New South Wales', 'Sydney', 88),
  ('MEL', 'Melbourne', 'Australia', 'Melbourne Airport', 'Victoria', 'Melbourne', 84),
  ('DOH', 'Doha', 'Qatar', 'Hamad International Airport', 'Doha', 'Doha', 90),
  ('MCT', 'Muscat', 'Oman', 'Muscat International Airport', 'Muscat', 'Muscat', 76),
  ('KUL', 'Kuala Lumpur', 'Malaysia', 'Kuala Lumpur International Airport', 'Selangor', 'Kuala Lumpur', 82),
  ('HKG', 'Hong Kong', 'China', 'Hong Kong International Airport', 'Hong Kong', 'Hong Kong', 88),
  ('ICN', 'Seoul', 'South Korea', 'Incheon International Airport', 'Incheon', 'Seoul', 88),
  ('FRA', 'Frankfurt', 'Germany', 'Frankfurt Airport', 'Hesse', 'Frankfurt', 86),
  ('AMS', 'Amsterdam', 'Netherlands', 'Amsterdam Airport Schiphol', 'North Holland', 'Amsterdam', 86),
  ('FCO', 'Rome', 'Italy', 'Leonardo da Vinci International Airport', 'Lazio', 'Rome', 82),
  ('ZRH', 'Zurich', 'Switzerland', 'Zurich Airport', 'Zurich', 'Zurich', 80);
